### ISSUE TITLE
Error when using: params['quant_isotopes'] = 'volume'

### ISSUE THREAD

**Issue by Gekkota95** [PASTAQ-MS/PASTAQ#5]
using
```python
params['quant_isotopes'] = 'volume'
```
leads to the following error:
```
Traceback (most recent call last):
  File "path\my_pastaq_file.py", line 48, in <module>
    pastaq.dda_pipeline(params, input_files, 'small_range', save_grid=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pastaq\__init__.py", line 2517, in dda_pipeline
    create_quantitative_tables(pastaq_parameters, output_dir, logger, force_override)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pastaq\__init__.py", line 1317, in create_quantitative_tables
    peak_clusters_df[stem] = [cluster.file_volumes[i]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pastaq\__init__.py", line 1317, in <listcomp>
    peak_clusters_df[stem] = [cluster.file_volumes[i]
AttributeError: 'pastaq.pastaq.PeakCluster' object has no attribute 'file_volumes'
```

you can solve this by changing line 1317/1318 in your "__init__.py" file in the pastaq package folder from:

```python
peak_clusters_df[stem] = [cluster.file_volumes[i]
                                          for cluster in peak_clusters]
```
to

```python
peak_clusters_df[stem] = [cluster.volumes[i]
                                          for cluster in peak_clusters]
```

**Comment by horvatovichlab** [comment]
The suggested modification has been made and commited. The issue is closed.
